/*
 * LED Config — binary config partition format
 *
 * Defines the LED configuration struct stored at offset 128
 * within the scratch partition.
 *
 * Generated by the UNAL Flash Tool web interface and flashed
 * alongside the firmware binary.
 *
 * Layout (64 bytes):
 *   Offset  Size  Field
 *   0x00    4     magic        (0x4C454443 = "LEDC")
 *   0x04    1     version      (1)
 *   0x05    1     mode         (0=solid,1=blink,2=breathe,3=rainbow)
 *   0x06    1     brightness   (0–255)
 *   0x07    1     speed        (1–255, animation tick rate)
 *   0x08    1     color_r      (primary R)
 *   0x09    1     color_g      (primary G)
 *   0x0A    1     color_b      (primary B)
 *   0x0B    1     flags        (reserved, 0)
 *   0x0C    52    reserved     (0xFF)
 */

#ifndef LED_CONFIG_H
#define LED_CONFIG_H

#include <stdint.h>

#define LED_CONFIG_MAGIC   0x4C454443  /* "LEDC" in ASCII */
#define LED_CONFIG_VERSION 1

/* LED behaviour modes */
enum led_mode {
	LED_MODE_SOLID        = 0,
	LED_MODE_BLINK        = 1,
	LED_MODE_BREATHE      = 2,
	LED_MODE_RAINBOW      = 3,
};

struct led_config {
	uint32_t magic;
	uint8_t  version;
	uint8_t  mode;
	uint8_t  brightness;
	uint8_t  speed;
	uint8_t  color_r;
	uint8_t  color_g;
	uint8_t  color_b;
	uint8_t  flags;
	uint8_t  reserved[52];
} __attribute__((packed));

_Static_assert(sizeof(struct led_config) == 64,
	       "led_config struct must be 64 bytes");

/**
 * Read LED config from the config flash partition (offset 128).
 * Populates *cfg on success.  Returns 0 if valid, -1 otherwise.
 */
int led_config_load(struct led_config *cfg);

/**
 * Fill cfg with sensible defaults (wifi_status mode, white, full brightness).
 */
void led_config_defaults(struct led_config *cfg);

#endif /* LED_CONFIG_H */
