/*
 * WiFi Config — binary config partition format
 *
 * Defines the binary struct that is stored at a fixed flash offset
 * and generated by the UNAL Flash Tool web interface.
 *
 * The web tool generates this blob in the browser and flashes it
 * alongside the firmware binary — no serial provisioning needed.
 *
 * Layout (128 bytes total, 4KB-aligned for flash sector erase):
 *   Offset  Size  Field
 *   0x00    4     magic       (0x57494649 = "WIFI")
 *   0x04    1     version     (1)
 *   0x05    1     ssid_len
 *   0x06    1     psk_len
 *   0x07    1     flags       (reserved)
 *   0x08    33    ssid        (null-terminated, max 32 chars)
 *   0x29    65    psk         (null-terminated, max 64 chars)
 *   0x6A    22    reserved    (0xFF padding)
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#include <stdint.h>
#include <stddef.h>

#define WIFI_CONFIG_MAGIC      0x57494649  /* "WIFI" in ASCII */
#define WIFI_CONFIG_VERSION    1
#define WIFI_CONFIG_SSID_MAX   32
#define WIFI_CONFIG_PSK_MAX    64

struct wifi_config {
	uint32_t magic;
	uint8_t  version;
	uint8_t  ssid_len;
	uint8_t  psk_len;
	uint8_t  flags;
	char     ssid[WIFI_CONFIG_SSID_MAX + 1];
	char     psk[WIFI_CONFIG_PSK_MAX + 1];
	uint8_t  reserved[22];
} __attribute__((packed));

/* Compile-time check: struct must be exactly 128 bytes */
_Static_assert(sizeof(struct wifi_config) == 128,
	       "wifi_config struct must be 128 bytes");

/**
 * Read WiFi config from the config flash partition.
 * Returns 0 if a valid config was found, -1 otherwise.
 */
int wifi_config_load(char *ssid, size_t ssid_len,
		     char *psk, size_t psk_len);

#endif /* WIFI_CONFIG_H */
