"use client";

import { useState, useCallback } from "react";
import { useSerial } from "@/hooks/useSerial";
import { CredentialWriter } from "@/lib/credentials/CredentialWriter";

interface CredentialField {
  key: string;
  label: string;
  type: "text" | "password" | "textarea" | "file";
  placeholder: string;
  group: string;
}

const CREDENTIAL_FIELDS: CredentialField[] = [
  // WiFi
  { key: "wifi_ssid", label: "WiFi SSID", type: "text", placeholder: "MyNetwork", group: "WiFi" },
  { key: "wifi_password", label: "WiFi Password", type: "password", placeholder: "••••••••", group: "WiFi" },
  // MQTT
  { key: "mqtt_broker", label: "Broker URL", type: "text", placeholder: "mqtt://broker.example.com:1883", group: "MQTT" },
  { key: "mqtt_user", label: "Username", type: "text", placeholder: "mqtt_user", group: "MQTT" },
  { key: "mqtt_password", label: "Password", type: "password", placeholder: "••••••••", group: "MQTT" },
  { key: "mqtt_topic", label: "Base Topic", type: "text", placeholder: "devices/esp32", group: "MQTT" },
  // API Keys
  { key: "api_key", label: "API Key", type: "password", placeholder: "sk-...", group: "API Keys" },
  { key: "api_endpoint", label: "API Endpoint", type: "text", placeholder: "https://api.example.com", group: "API Keys" },
  // Device Identity
  { key: "device_id", label: "Device ID", type: "text", placeholder: "esp32-001", group: "Device Identity" },
  { key: "device_name", label: "Device Name", type: "text", placeholder: "Sensor Node 1", group: "Device Identity" },
];

const CERT_FIELDS = [
  { key: "tls_ca_cert", label: "CA Certificate", group: "TLS Certificates" },
  { key: "tls_client_cert", label: "Client Certificate", group: "TLS Certificates" },
  { key: "tls_client_key", label: "Client Private Key", group: "TLS Certificates" },
];

export default function CredentialEditor() {
  const serial = useSerial();
  const [values, setValues] = useState<Record<string, string>>({});
  const [certs, setCerts] = useState<Record<string, string>>({});
  const [status, setStatus] = useState<"idle" | "writing" | "success" | "error">("idle");
  const [statusMsg, setStatusMsg] = useState("");
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>({
    WiFi: true,
  });

  const handleChange = useCallback((key: string, value: string) => {
    setValues((prev) => ({ ...prev, [key]: value }));
  }, []);

  const handleCertUpload = useCallback((key: string, e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      setCerts((prev) => ({ ...prev, [key]: reader.result as string }));
    };
    reader.readAsText(file);
  }, []);

  const toggleGroup = useCallback((group: string) => {
    setExpandedGroups((prev) => ({ ...prev, [group]: !prev[group] }));
  }, []);

  const handleWrite = useCallback(async () => {
    if (serial.state !== "connected") {
      setStatus("error");
      setStatusMsg("Device not connected. Connect via the Terminal or Flash page first.");
      return;
    }

    setStatus("writing");
    setStatusMsg("Writing credentials to device NVS...");

    try {
      const writer = new CredentialWriter();

      // Filter non-empty credentials
      const credentials: Record<string, string> = {};
      for (const [key, value] of Object.entries(values)) {
        if (value.trim()) credentials[key] = value.trim();
      }

      // Filter non-empty certs
      const certificates: Record<string, string> = {};
      for (const [key, value] of Object.entries(certs)) {
        if (value.trim()) certificates[key] = value;
      }

      if (Object.keys(credentials).length === 0 && Object.keys(certificates).length === 0) {
        setStatus("error");
        setStatusMsg("No credentials to write. Fill in at least one field.");
        return;
      }

      const result = await writer.writeAll(credentials, certificates);

      if (result.success) {
        setStatus("success");
        setStatusMsg(`Successfully written ${Object.keys(credentials).length + Object.keys(certificates).length} credential(s) to device.`);
      } else {
        setStatus("error");
        setStatusMsg(`Errors: ${result.errors.join(", ")}`);
      }
    } catch (err) {
      setStatus("error");
      setStatusMsg(err instanceof Error ? err.message : "Failed to write credentials");
    }
  }, [serial.state, values, certs]);

  const handleExportOverlay = useCallback(() => {
    const lines: string[] = [
      "# Zephyr Kconfig Overlay — Generated by UNAL Flash Tool",
      `# ${new Date().toISOString()}`,
      "",
    ];

    for (const [key, value] of Object.entries(values)) {
      if (value.trim()) {
        const kconfigKey = `CONFIG_${key.toUpperCase()}`;
        lines.push(`${kconfigKey}="${value}"`);
      }
    }

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "overlay.conf";
    a.click();
    URL.revokeObjectURL(url);
  }, [values]);

  // Group fields
  const groups = new Map<string, CredentialField[]>();
  for (const field of CREDENTIAL_FIELDS) {
    if (!groups.has(field.group)) groups.set(field.group, []);
    groups.get(field.group)!.push(field);
  }

  return (
    <div className="space-y-6">
      {/* Status banner */}
      {status !== "idle" && (
        <div
          className={`rounded-lg p-4 text-sm border ${
            status === "writing"
              ? "bg-blue-900/20 border-blue-800 text-blue-300"
              : status === "success"
                ? "bg-green-900/20 border-green-800 text-green-300"
                : "bg-red-900/20 border-red-800 text-red-300"
          }`}
        >
          {statusMsg}
        </div>
      )}

      {/* Credential Groups */}
      {Array.from(groups.entries()).map(([group, fields]) => (
        <div key={group} className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
          <button
            onClick={() => toggleGroup(group)}
            className="w-full flex items-center justify-between p-4 hover:bg-gray-800/50 transition-colors"
          >
            <h3 className="text-white font-medium">{group}</h3>
            <svg
              className={`w-5 h-5 text-gray-500 transition-transform ${expandedGroups[group] ? "rotate-180" : ""}`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>

          {expandedGroups[group] && (
            <div className="px-4 pb-4 space-y-3">
              {fields.map((field) => (
                <div key={field.key}>
                  <label className="text-sm text-gray-400 block mb-1">{field.label}</label>
                  <input
                    type={field.type}
                    placeholder={field.placeholder}
                    value={values[field.key] || ""}
                    onChange={(e) => handleChange(field.key, e.target.value)}
                    className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-gray-200 text-sm placeholder-gray-600 focus:outline-none focus:border-blue-600"
                  />
                </div>
              ))}
            </div>
          )}
        </div>
      ))}

      {/* Certificates */}
      <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
        <button
          onClick={() => toggleGroup("TLS Certificates")}
          className="w-full flex items-center justify-between p-4 hover:bg-gray-800/50 transition-colors"
        >
          <h3 className="text-white font-medium">TLS Certificates</h3>
          <svg
            className={`w-5 h-5 text-gray-500 transition-transform ${expandedGroups["TLS Certificates"] ? "rotate-180" : ""}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {expandedGroups["TLS Certificates"] && (
          <div className="px-4 pb-4 space-y-3">
            {CERT_FIELDS.map((field) => (
              <div key={field.key}>
                <label className="text-sm text-gray-400 block mb-1">{field.label}</label>
                <div className="flex items-center gap-2">
                  <label className="flex-1 relative">
                    <div className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-400 cursor-pointer hover:bg-gray-750">
                      {certs[field.key] ? "✓ File loaded" : "Choose .pem file..."}
                    </div>
                    <input
                      type="file"
                      accept=".pem,.crt,.key"
                      onChange={(e) => handleCertUpload(field.key, e)}
                      className="hidden"
                    />
                  </label>
                  {certs[field.key] && (
                    <button
                      onClick={() =>
                        setCerts((prev) => {
                          const next = { ...prev };
                          delete next[field.key];
                          return next;
                        })
                      }
                      className="p-2 text-gray-500 hover:text-red-400"
                    >
                      ✕
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex gap-3 flex-wrap">
        <button
          onClick={handleWrite}
          disabled={status === "writing" || serial.state !== "connected"}
          className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 disabled:text-gray-500 text-white rounded-lg text-sm font-medium transition-colors"
        >
          {status === "writing" ? "Writing..." : "Write to Device (NVS)"}
        </button>
        <button
          onClick={handleExportOverlay}
          className="px-4 py-2.5 bg-gray-800 hover:bg-gray-700 text-gray-300 rounded-lg text-sm border border-gray-700 transition-colors"
        >
          Export overlay.conf
        </button>
      </div>

      <p className="text-xs text-gray-600">
        NVS: Writes credentials at runtime via PROV:* serial protocol. overlay.conf: Generates a Kconfig
        overlay for build-time injection.
      </p>
    </div>
  );
}
